### ISSUE TITLE
High density region labels are calculated only for one of the two groups

### ISSUE THREAD

**Issue by MTB-gbrugnaro** [poloclub/wizmap#16]
High density region labels are calculated only for one of the two groups:
<img width="928" alt="Screenshot 2023-09-29 at 07 06 52" src="https://github.com/poloclub/wizmap/assets/73693213/95630318-164c-41e7-801f-e2bb39369a2c">

**Comment by xiaohk** [comment]
23551398a96bffbfe0863219d76fa1a483879be9 should fix this issue. You can increate the label count to see more labels around high density regions on both groups. Feel free to re-open the issue if you have any more questions. Thanks!!
