### ISSUE TITLE
Embeddings now showing

### ISSUE THREAD

**Issue by thetradingwhisperer** [poloclub/wizmap#18]
When I load the embeddings provided in the demo, it shows empty no matter what I do.

**Comment by xiaohk** [comment]
Hello @thetradingwhisperer!

Can you share the WizMap URL you are using? Are there any errors in the browser console?

#### Shortcuts to open browser consoles

|OS|Browser|Shortcut|
|:---|:---|:---|
|macOS|Safari|Option + ⌘ + C|
|macOS|Chrome|Option + ⌘ + J| 
|macOS|Firefox|Option + ⌘ + K| 
|Windows|Edge|Ctrl + Shift + J| 
|Windows|Chrome|Ctrl + Shift + J| 
|Windows|Firefox|Ctrl + Shift + K|
