### ISSUE TITLE
How to load the visualisation in an iframe on our website?

### ISSUE THREAD

**Issue by Sahas** [poloclub/wizmap#22]
We created a visualisation and have a link. We want to showcase the visualisation in our website and tried to use iframe for the same but the visualisation is not loading. 

Is there a way we can load the visualisations on our own website?

**Comment by xiaohk** [comment]
Hi! Yes, iframe should work. Here is a demo: https://codepen.io/xiaohk/pen/WNWxVwJ

<img width="1433" alt="image" src="https://github.com/poloclub/wizmap/assets/15007159/04a393d2-aaa8-4af0-b3d3-48cb9ad252ac">


Let me know if you have more questions.
