### ISSUE TITLE
No points are displayed

### ISSUE THREAD

**Issue by tsdev** [poloclub/wizmap#3]
I am running locally WizMap but only contours are visible, see below showing the DiffusionDB example. I am running WizMap in the command line:
```bash
❯ npm run dev


> wizmap@0.1.1 dev
> vite --port 3000


  VITE v3.2.7  ready in 182 ms

  ➜  Local:   http://localhost:3000/
  ➜  Network: use --host to expose
10:50:36 AM [vite-plugin-svelte] /src/components/mapview/MapView.svelte:70:0 Unused CSS selector ".main-app-container.hidden"
10:50:36 AM [vite-plugin-svelte] /src/components/footer/Footer.svelte:250:0 Unused CSS selector "dialog[open] .row-block .row-name"
```

<img width="1040" alt="image" src="https://github.com/poloclub/wizmap/assets/9294105/7078ee63-fd8c-49f5-84de-cc447070f1dc">

**Comment by xiaohk** [comment]
Hi @tsdev, did you see any error in the console of your web browser? It looks like you are loading the DiffusionDB example, which might take some time to load the data.

**Comment by tsdev** [comment]
I see the following message in the terminal:
```bash
11:43:12 AM [vite-plugin-svelte] /src/components/mapview/MapView.svelte:70:0 Unused CSS selector ".main-app-container.hidden"
11:43:12 AM [vite-plugin-svelte] /src/components/footer/Footer.svelte:250:0 Unused CSS selector "dialog[open] .row-block .row-name"
```

**Comment by tsdev** [comment]
Data points are shown for the ACL Abstracts and IMDB Reviews examples, only failing for the DiffusionDB example.

**Comment by xiaohk** [comment]
> I see the following message in the terminal:
> 
> ```shell
> 11:43:12 AM [vite-plugin-svelte] /src/components/mapview/MapView.svelte:70:0 Unused CSS selector ".main-app-container.hidden"
> 11:43:12 AM [vite-plugin-svelte] /src/components/footer/Footer.svelte:250:0 Unused CSS selector "dialog[open] .row-block .row-name"
> ```

Sorry for the late reply! I'm busy working for a deadline. Can you check your web browser's console to see if there is any warning or error?

#### Shortcuts to open browser consoles

|OS|Browser|Shortcut|
|:---|:---|:---|
|macOS|Safari|Option + ⌘ + C|
|macOS|Chrome|Option + ⌘ + J| 
|macOS|Firefox|Option + ⌘ + K| 
|Windows|Edge|Ctrl + Shift + J| 
|Windows|Chrome|Ctrl + Shift + J| 
|Windows|Firefox|Ctrl + Shift + K|

**Comment by xiaohk** [comment]
> * https://gist.githubusercontent.com/carschno/f9e73a69a55d5a85fb0237585a79e75a/raw/6d0617812afd26a1842d0924e9c3ffa52bf9122d/grid.json

Hello @carschno, sorry for the late reply. I'm busy working on a deadline 😵‍💫.

In your case, the points are actually shown but the color is too light to see. When I get a chance, I will improve the color setting in WizMap.

<img width="986" alt="image" src="https://github.com/poloclub/wizmap/assets/15007159/7239ad9a-1e6d-408d-bc14-088a79ddfda5">

**Comment by carschno** [comment]
True, I can confirm, and thanks for looking into it!

No errors or warnings in the browser console btw, but I suppose that has now been expected.
