### ISSUE TITLE
How can I display images?

### ISSUE THREAD

**Issue by tsdev** [poloclub/wizmap#4]
I would like to display an image for each data point, can you please provide an example code how to do that? Thank you!

**Comment by xiaohk** [comment]
Thanks! I will add an example soon. To show images instead of text, you just need to specify the image urls in the two JSON files. Take DiffusionDB as an example.

In the `diffusiondb.json` file, we specify the image URL prefix.

```
{'image': {'imageGroup': 1,
  'imageURLPrefix': 'https://raw.githubusercontent.com/poloclub/diffusiondb-thumbnails/master/'}}
```

In the `diffusiondb.ndjson` file, we specify the rest of the URL for each image point.

```
[-4.7069817,
  4.4307537,
  '3f/3f72a44a-1b36-4de8-bd2a-68046e844429.webp',
  '',
  1],
 [-3.5961475,
  -3.2497282,
  '24/240c16c6-ab4d-4bd4-8519-7a153d59d137.webp',
  '',
  1],
 [-0.15707111,
  -1.4298916,
  '31/317a6218-382c-4dbd-938f-a82d558769a7.webp',
  '',
  1]
```

**Comment by tsdev** [comment]
Thank you!

**Comment by RBZ-99** [comment]
Hi, were you able to visualize images when you hover over the data points? For me the Diffusion-DB example only shows the link to the image and doesn't display the image exactly

**Comment by xiaohk** [comment]
> Hi, were you able to visualize images when you hover over the data points? For me the Diffusion-DB example only shows the link to the image and doesn't display the image exactly

Hi! I just tried https://poloclub.github.io/wizmap/?dataset=diffusiondb, and I can see the images. Which browser do you use? What's your browser version?

**Comment by RBZ-99** [comment]
Thanks a lot! Opened in another system and it worked.
