### ISSUE TITLE
please check the link, why the blue contour cover all the point?

### ISSUE THREAD

**Issue by Bdl-1989** [poloclub/wizmap#9]
https://poloclub.github.io/wizmap/?dataURL=https%3A%2F%2Fhuggingface.co%2Fdatasets%2Fbobdingli%2FTESTWIZMAP%2Fresolve%2Fmain%2Fdata.ndjson&gridURL=https%3A%2F%2Fhuggingface.co%2Fdatasets%2Fbobdingli%2FTESTWIZMAP%2Fresolve%2Fmain%2Fgrid.json

point can switch "true" and "gene" points respectively
however, the blue contour cover all the points region

**Comment by Bdl-1989** [comment]
![image](https://github.com/poloclub/wizmap/assets/48614612/a7bce983-16ee-4540-971d-986b3fb70945)
is the reason?

**Comment by Bdl-1989** [comment]
I raise a PR
https://github.com/poloclub/wizmap/pull/10

**Comment by xiaohk** [comment]
Hi @Bdl-1989, thank you so much for raising the error. I can reproduce the error. I'm busy with a deadline right now. I will look into it when I have more time.

**Comment by xiaohk** [comment]
Hello @Bdl-1989! Sorry for the late reply! https://github.com/poloclub/wizmap/commit/025342dc17e474918f2eeb5329c111df7e486382 fixed this issue.

You can visit the link https://poloclub.github.io/wizmap/?dataURL=https%3A%2F%2Fhuggingface.co%2Fdatasets%2Fbobdingli%2FTESTWIZMAP%2Fresolve%2Fmain%2Fdata.ndjson&gridURL=https%3A%2F%2Fhuggingface.co%2Fdatasets%2Fbobdingli%2FTESTWIZMAP%2Fresolve%2Fmain%2Fgrid.json again to see the new update.

Thanks for reporting this bug!
